name: GitOps CD Workflow

on:
  # repository_dispatch:
  #   types: [deploy]
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image tag to deploy"
        required: true
      env:
        description: "Environment (dev/qa/prod)"
        required: true
        type: choice
        options: [dev, qa, prod]

jobs:
  update-helm-values:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env || github.event.client_payload.env }}

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4

      - name: Set IMAGE + ENV
        run: |
          if [ -n "${{ github.event.client_payload.image }}" ]; then
            echo "IMAGE=${{ github.event.client_payload.image }}" >> $GITHUB_ENV
            echo "ENV=${{ github.event.client_payload.env }}" >> $GITHUB_ENV
          else
            echo "IMAGE=${{ github.event.inputs.image }}" >> $GITHUB_ENV
            echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          fi

      - name: Update Helm values.yaml
        run: |
          IMAGE_REPO=$(echo ${{ env.IMAGE }} | cut -d: -f1)
          IMAGE_TAG=$(echo ${{ env.IMAGE }} | cut -d: -f2)
          yq e -i ".image.repository = \"$IMAGE_REPO\"" envs/${{ env.ENV }}/values.yaml
          yq e -i ".image.tag = \"$IMAGE_TAG\"" envs/${{ env.ENV }}/values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Deploy ${{ env.IMAGE }} to ${{ env.ENV }}"
          branch: "deploy/${{ env.ENV }}-${{ env.IMAGE }}"
          title: "Promote ${{ env.IMAGE }} to ${{ env.ENV }}"
          body: |
            This PR updates the `${{ env.ENV }}` environment to use:
            ```
            Image: ${{ env.IMAGE }}
            ```
          labels: ["deployment", "${{ env.ENV }}"]
          reviewers: team-lead, ops-engineer   # 👈 require human approval
